"""
SPSS main export pipeline for NeuroCogEEG.

This script creates reduced SPSS-ready main analysis CSV files using the
column-selection plan generated by pipelines/spss_main_column_plan.py.

It does not modify original result CSV files.

Outputs:
- outputs/flanker/csv/flanker_spss_main.csv
- outputs/gonogo/csv/gonogo_spss_main.csv
- outputs/readysetgo/csv/readysetgo_spss_main.csv
- outputs/tmt/csv/tmt_spss_main.csv
- outputs/qc/spss_main_export_summary.csv
"""

import sys
from pathlib import Path

import pandas as pd


PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))


PLAN_PATH = PROJECT_ROOT / "outputs" / "qc" / "spss_main_column_plan.csv"

RESULT_FILES = {
    "flanker": PROJECT_ROOT / "outputs" / "flanker" / "csv" / "flanker_results.csv",
    "gonogo": PROJECT_ROOT / "outputs" / "gonogo" / "csv" / "gonogo_results.csv",
    "readysetgo": PROJECT_ROOT / "outputs" / "readysetgo" / "csv" / "readysetgo_results.csv",
    "tmt": PROJECT_ROOT / "outputs" / "tmt" / "csv" / "tmt_results.csv",
}

OUTPUT_FILES = {
    "flanker": PROJECT_ROOT / "outputs" / "flanker" / "csv" / "flanker_spss_main.csv",
    "gonogo": PROJECT_ROOT / "outputs" / "gonogo" / "csv" / "gonogo_spss_main.csv",
    "readysetgo": PROJECT_ROOT / "outputs" / "readysetgo" / "csv" / "readysetgo_spss_main.csv",
    "tmt": PROJECT_ROOT / "outputs" / "tmt" / "csv" / "tmt_spss_main.csv",
}


def read_csv(path):
    return pd.read_csv(
        path,
        sep=";",
        decimal=",",
        encoding="utf-8-sig",
    )


def write_csv(dataframe, path):
    path.parent.mkdir(parents=True, exist_ok=True)

    dataframe.to_csv(
        path,
        sep=";",
        decimal=",",
        encoding="utf-8-sig",
        index=False,
    )


def normalize_keep_value(value):
    if isinstance(value, bool):
        return value

    text = str(value).strip().lower()

    return text in ["true", "1", "yes"]


def get_kept_columns(plan, experiment):
    experiment_plan = plan[plan["experiment"] == experiment].copy()

    experiment_plan["keep_bool"] = experiment_plan["keep"].apply(
        normalize_keep_value
    )

    kept_plan = experiment_plan[experiment_plan["keep_bool"] == True]

    return kept_plan["column"].tolist()


def check_missing_columns(dataframe, columns):
    return [column for column in columns if column not in dataframe.columns]


def convert_minimum_flags_to_numeric(dataframe):
    """
    Convert minimum trial pass/fail columns to numeric 1/0.

    This is more convenient for SPSS than True/False text.
    """
    converted = dataframe.copy()

    flag_columns = [
        column
        for column in converted.columns
        if column.endswith("_minimum_met")
    ]

    for column in flag_columns:
        series = converted[column]

        if series.dtype == bool:
            converted[column] = series.astype("Int64")
            continue

        text = series.astype(str).str.strip().str.lower()

        converted[column] = text.map(
            {
                "true": 1,
                "false": 0,
                "1": 1,
                "0": 0,
                "yes": 1,
                "no": 0,
            }
        ).astype("Int64")

    return converted


def check_suspicious_columns(columns):
    event_name_columns = {
        "stimulus",
        "correct_response",
        "error_response",
        "missed_response",
        "ready",
        "set",
        "go_response",
        "task_start",
        "correct_click",
        "error_click",
        "task_end",
    }

    suspicious = []

    for column in columns:
        if column.startswith("raw_"):
            suspicious.append(column)
        elif column.startswith("qc_"):
            suspicious.append(column)
        elif column.startswith("event_count_"):
            suspicious.append(column)
        elif column in event_name_columns:
            suspicious.append(column)

    return suspicious


def export_one_experiment(experiment, plan):
    result_path = RESULT_FILES[experiment]
    output_path = OUTPUT_FILES[experiment]

    if not result_path.exists():
        raise FileNotFoundError(f"Result file not found: {result_path}")

    result_df = read_csv(result_path)

    kept_columns = get_kept_columns(
        plan=plan,
        experiment=experiment,
    )

    missing_columns = check_missing_columns(
        dataframe=result_df,
        columns=kept_columns,
    )

    if missing_columns:
        raise ValueError(
            f"{experiment}: planned columns missing from result file: "
            f"{missing_columns}"
        )

    suspicious_columns = check_suspicious_columns(kept_columns)

    if suspicious_columns:
        raise ValueError(
            f"{experiment}: suspicious columns selected for SPSS main file: "
            f"{suspicious_columns}"
        )

    main_df = result_df[kept_columns].copy()
    main_df = convert_minimum_flags_to_numeric(main_df)

    write_csv(main_df, output_path)

    return {
        "experiment": experiment,
        "input_file": str(result_path),
        "output_file": str(output_path),
        "row_count": int(len(main_df)),
        "column_count": int(len(main_df.columns)),
        "minimum_flag_columns": "; ".join(
            column
            for column in main_df.columns
            if column.endswith("_minimum_met")
        ),
    }


def main():
    if not PLAN_PATH.exists():
        raise FileNotFoundError(
            f"SPSS column plan not found: {PLAN_PATH}. "
            "Run pipelines/spss_main_column_plan.py first."
        )

    plan = read_csv(PLAN_PATH)

    summary_rows = []

    for experiment in RESULT_FILES:
        summary = export_one_experiment(
            experiment=experiment,
            plan=plan,
        )
        summary_rows.append(summary)

    summary_df = pd.DataFrame(summary_rows)

    summary_path = PROJECT_ROOT / "outputs" / "qc" / "spss_main_export_summary.csv"

    write_csv(summary_df, summary_path)

    print("SPSS ana analiz dosyaları oluşturuldu.")
    print("")
    print(summary_df[["experiment", "row_count", "column_count", "output_file"]])
    print("")
    print(f"Özet dosyası: {summary_path}")


if __name__ == "__main__":
    main()